/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JmSideDrawer {
    }
}
declare global {
    interface HTMLJmSideDrawerElement extends Components.JmSideDrawer, HTMLStencilElement {
    }
    var HTMLJmSideDrawerElement: {
        prototype: HTMLJmSideDrawerElement;
        new (): HTMLJmSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "jm-side-drawer": HTMLJmSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface JmSideDrawer {
    }
    interface IntrinsicElements {
        "jm-side-drawer": JmSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jm-side-drawer": LocalJSX.JmSideDrawer & JSXBase.HTMLAttributes<HTMLJmSideDrawerElement>;
        }
    }
}
